name: publish-prerelease:npm

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-scripts
      - run: yarn run ci:test

  npm-publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
      - run: yarn install --ignore-scripts
      - run: yarn prepack
      - run: npm publish --tag beta
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}